### ISSUE TITLE
Failure at package identification

### ISSUE THREAD

**Issue by FluffyDietEngine** [FluffyDietEngine/wall-e#7]
Release 0.2.0 shipped with major error due to lack of testing. Bug 

```python
Traceback (most recent call last):
  File "/Users/santhoshsolomon/Projects/learning/df_comparison/venv/bin/package-sieve", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/santhoshsolomon/Projects/learning/df_comparison/venv/lib/python3.11/site-packages/src/wall_e.py", line 145, in main
    modules = traverse_directory(args.project_folder, ignore_directories)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/santhoshsolomon/Projects/learning/df_comparison/venv/lib/python3.11/site-packages/src/wall_e.py", line 85, in traverse_directory
    modules = get_modules_from_file(item)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/santhoshsolomon/Projects/learning/df_comparison/venv/lib/python3.11/site-packages/src/wall_e.py", line 61, in get_modules_from_file
    collector.visit(node)
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py", line 418, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py", line 426, in generic_visit
    self.visit(item)
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py", line 418, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/Users/santhoshsolomon/Projects/learning/df_comparison/venv/lib/python3.11/site-packages/src/wall_e.py", line 39, in visit_ImportFrom
    if "site-packages" in __import__(module).__file__:
                          ^^^^^^^^^^^^^^^^^^
TypeError: module name must be a string
```

**Comment by FluffyDietEngine** [comment]
The above issue has happened because of two different reasons. 
1. `.gitignore` file was not considered to get `ignore_patterns` in the main method. 
2.  Due to which, a module without a name, became `NoneType`  and failed the code. 

Fix:
1. Hardcode the folders which are in `.gitignore` file, as it is not susceptible to change, instead of getting into overhead of managing file location.
2. Exception handling for `TypeError`.
